name: icomoon_generator
description: >-
  A Dart package that generates Flutter-compatible class.
  This class contains static const IconData fields for each icon in your IcoMoon selection.
version: 1.0.3
homepage: https://github.com/thanhhaidev/icomoon_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.6.0
  collection: ^1.19.0
  dart_style: ^3.0.1
  logger: ^2.5.0
  path: ^1.9.0
  recase: ^4.1.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.14

executables:
  generator: generator
