name: icomoon_generator
description: >-
  A Dart package that generates Flutter-compatible class.
  This class contains static const IconData fields for each icon in your IcoMoon selection.
version: 0.0.5
homepage: https://github.com/thanhhaidev/icomoon_generator

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  args: ^2.4.2
  collection: ^1.17.0
  dart_style: ^2.3.0
  logger: ^2.0.2+1
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.9

executables:
  generator: generator
